add validation for the new zstd inline compression user variables

diff --git a/script b/script
--- a/script
+++ b/script
@@ -1434,27 +1434,60 @@ only_send_error_notifications="0"
   fi
 
 
-  # check to see if backups should be compressed. if yes, continue. if no, continue. if input invalid, exit.
-  if [[ "$compress_backups" =~ ^(0|1)$ ]]; then
+  # check to see if vdisks should be inline compressed.
+  if [[ ! "$inline_zstd_compress" =~ ^(0|1)$ ]]; then
+    log_message "failure: inline_zstd_compress is $inline_zstd_compress. this is not a valid format. expecting [0 = no] or [1 = yes]. exiting." "script failed" "alert"
+    exit 1
+  elif [ "$inline_zstd_compress" -eq 0 ]; then
+    log_message "information: inline_zstd_compress is $inline_zstd_compress. vdisk images will not be inline compressed."
+  elif [ "$inline_zstd_compress" -eq 1 ]; then
+    log_message "information: inline_zstd_compress is $inline_zstd_compress. vdisk images will be inline compressed but will not be compared afterwards or post compressed."
+  fi
 
-    if [ "$compress_backups" -eq 0 ]; then
+  # if inline_zstd_compress is enabled, check to see if zstd_level and zstd_threads are valid and in range.
+  if [ "$inline_zstd_compress" -eq 1 ]; then
 
-      log_message "information: compress_backups is $compress_backups. backups will not be compressed."
-
-    elif [ "$compress_backups" -eq 1 ]; then
-
-      log_message "information: compress_backups is $compress_backups. backups will be compressed."
-
+    # check to see if zstd_level is valid and in range.
+    if [[ ! "$zstd_level" =~ ^[0-9]+$ ]]; then
+      log_message "failure: zstd_level is $zstd_level. this is not a valid format. expecting a number between [1 - 19]. exiting." "script failed" "alert"
+      exit 1
+    elif [ "$zstd_level" -lt 1 ] || [ "$zstd_level" -gt 19 ] ; then
+      log_message "failure: zstd_level is $zstd_level. expecting a number between [1 - 19]. exiting." "script failed" "alert"
+      exit 1
+    elif [ "$zstd_level" -gt 8 ] ; then
+      log_message "warning: zstd_level is $zstd_level. this will be slower and may not produce meaningfully smaller backup images."
+    else
+      log_message "information: zstd_level is $zstd_level."
     fi
 
-  else
-
-    log_message "failure: compress_backups is $compress_backups. this is not a valid format. expecting [0 = no] or [1 = yes]. exiting." "script failed" "alert"
-
-    exit 1
+    # check to see if zstd_threads is valid and in range.
+    if [[ ! "$zstd_threads" =~ ^[0-9]+$ ]]; then
+      log_message "failure: zstd_threads is $zstd_threads. this is not a valid format. expecting a number between [0 - 200]. exiting." "script failed" "alert"
+      exit 1
+    elif [ "$zstd_threads" -lt 0 ] || [ "$zstd_threads" -gt 200 ] ; then
+      log_message "failure: zstd_threads is $zstd_threads. expecting a number between [0 - 200]. exiting." "script failed" "alert"
+      exit 1
+    elif [ "$zstd_threads" -gt 4 ] ; then
+      log_message "warning: zstd_threads is $zstd_threads. this is a lot of threads to use for compression."
+    elif [ "$zstd_threads" -eq 0 ] ; then
+      log_message "information: zstd_threads is $zstd_threads. the actual number of threads will be auto determined."
+    else
+      log_message "information: zstd_threads is $zstd_threads."
+    fi
 
   fi
 
+  # if inline_zstd_compress is disabled, check to see if backups should be post compressed.
+  if [ "$inline_zstd_compress" -ne 1 ]; then
+    if [[ ! "$compress_backups" =~ ^(0|1)$ ]]; then
+      log_message "failure: compress_backups is $compress_backups. this is not a valid format. expecting [0 = no] or [1 = yes]. exiting." "script failed" "alert"
+      exit 1
+    elif [ "$compress_backups" -eq 0 ]; then
+      log_message "information: compress_backups is $compress_backups. backups will not be post compressed."
+    elif [ "$compress_backups" -eq 1 ]; then
+      log_message "information: compress_backups is $compress_backups. backups will be post compressed."
+    fi
+  fi
 
   #### advanced variables ####
 
@@ -1578,28 +1611,17 @@ only_send_error_notifications="0"
 
   fi
 
-
-  # check to see if files should be compared after backup. if yes, continue. if no, continue. if input invalid, exit.
-  if [[ "$compare_files" =~ ^(0|1)$ ]]; then
-
-    if [ "$compare_files" -eq 0 ]; then
-
+  # if inline_zstd_compress is disabled, check to see if files should be compared after backup.
+  if [ "$inline_zstd_compress" -ne 1 ]; then
+    if [[ ! "$compare_files" =~ ^(0|1)$ ]]; then
+      log_message "failure: compare_files is $compare_files. this is not a valid format. expecting [0 = no] or [1 = yes]. exiting." "script failed" "alert"
+      exit 1
+    elif [ "$compare_files" -eq 0 ]; then
       log_message "information: compare_files is $compare_files. files will not be compared after backups."
-
     elif [ "$compare_files" -eq 1 ]; then
-
       log_message "information: compare_files is $compare_files. files will be compared after backups."
-
     fi
-
-  else
-
-    log_message "failure: compare_files is $compare_files. this is not a valid format. expecting [0 = no] or [1 = yes]. exiting." "script failed" "alert"
-
-    exit 1
-
   fi
-
 
   # check to see if config should be backed up. if yes, continue. if no, continue. if input invalid, exit.
   if [[ "$backup_xml" =~ ^(0|1)$ ]]; then
