added option to ignore iso files during vdisk checks

diff --git a/script b/script
--- a/script
+++ b/script
@@ -28,7 +28,7 @@ enabled="0"
 # backup location to put vdisks.
 backup_location="/mnt/user/share/backup_folder/"
 
-# list of domains that will be backed up seperated by a new line.
+# list of domains that will be backed up separated by a new line.
 vms_to_backup="
 vm1
 vm2
@@ -68,7 +68,7 @@ keep_log_file="1"
 # default is 1. number of successful log files to keep. 0 means infinitely.
 number_of_log_files_to_keep="1"
 
-# default is "logs". set to "" to put in root of backups folder. set to "logs/<subfolder>" to keep logs separate if running multipe versions of this script.
+# default is "logs". set to "" to put in root of backups folder. set to "logs/<subfolder>" to keep logs separate if running multiple versions of this script.
 log_file_subfolder="logs"
 
 # default is 1. set to 0 to prevent notification system from being used. Script failures that occur before logging can start, and before this variable is validated will still be sent.
@@ -92,6 +92,9 @@ backup_nvram="1"
 # default is 1. set to 0 if you would like to skip backing up vdisks. setting this to 0 will automatically disable compression.
 backup_vdisks="1"
 
+# default is 0. set to 1 if you would like iso files to be ignored when checking for valid vdisks.
+ignore_isos="0"
+
 # default is 0. set this to 1 if you would like to start a vm after it has successfully been backed up. will override set_vm_to_original_state when set to 1.
 start_vm_after_backup="0"
 
@@ -109,10 +112,10 @@ rsync_only="0"
 # WARNING: will not work unless rsync_only is set to 1. if this is set to 1 and rsync_only is set to 0, then backups will be partial and the script won't work correctly.
 actually_copy_files="1"
 
-# default is 20. set this to the number of times you would like to check if a clean shutdown of a vm has been successfull.
+# default is 20. set this to the number of times you would like to check if a clean shutdown of a vm has been successful.
 clean_shutdown_checks="20"
 
-# default is 30. set this to the number of seconds to wait in between checks to see if a clean shutdown has been successfull.
+# default is 30. set this to the number of seconds to wait in between checks to see if a clean shutdown has been successful.
 seconds_to_wait="30"
 
 # default is 1. set to 0 to have error log files deleted after the backup has completed.
@@ -693,16 +696,46 @@ else
 fi
 
 
-# check to see if vms should be started after a successfull backup. if yes, continue. if no, continue. if input invalid, exit.
+# check to see if iso files should be ignored when checking vdisks. if yes, continue. if no, continue. if input invalid, exit.
+if [[ "$ignore_isos" =~ ^(0|1)$ ]]; then
+
+	if [ "$ignore_isos" -eq 0 ]; then
+
+		echo "$(date '+%Y-%m-%d %H:%M') information: ignore_isos is $ignore_isos. iso files will not be ignored when checking vdisks." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
+
+		compress_backups="0"
+
+	elif [ "$ignore_isos" -eq 1 ]; then
+
+		echo "$(date '+%Y-%m-%d %H:%M') information: ignore_isos is $ignore_isos. iso files will be ignored when checking vdisks." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
+
+	fi
+
+else
+
+	echo "$(date '+%Y-%m-%d %H:%M') failure: ignore_isos is $ignore_isos. this is not a valid format. expecting [0 = no] or [1 = yes]. exiting." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log" && errors="1"
+
+	if [ "$send_notifications" -eq 1 ];then
+
+		/usr/local/emhttp/plugins/dynamix/scripts/notify -e "unraid-vmbackup_failure" -s "unRAID VM Backup script" -d "script failed" -i "alert" -m "$(date '+%Y-%m-%d %H:%M') failure: ignore_isos is $ignore_isos. this is not a valid format. expecting [0 = no] or [1 = yes]. exiting."
+
+	fi
+
+	exit 1
+
+fi
+
+
+# check to see if vms should be started after a successful backup. if yes, continue. if no, continue. if input invalid, exit.
 if [[ "$start_vm_after_backup" =~ ^(0|1)$ ]]; then
 
 	if [ "$start_vm_after_backup" -eq 0 ]; then
 
-		echo "$(date '+%Y-%m-%d %H:%M') information: start_vm_after_backup is $start_vm_after_backup. vms will not be started following successfull backup." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
+		echo "$(date '+%Y-%m-%d %H:%M') information: start_vm_after_backup is $start_vm_after_backup. vms will not be started following successful backup." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
 
 	elif [ "$start_vm_after_backup" -eq 1 ]; then
 
-		echo "$(date '+%Y-%m-%d %H:%M') information: start_vm_after_backup is $start_vm_after_backup vms will be started following a successfull backup." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
+		echo "$(date '+%Y-%m-%d %H:%M') information: start_vm_after_backup is $start_vm_after_backup vms will be started following a successful backup." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
 
 	fi
 
@@ -721,16 +754,16 @@ else
 fi
 
 
-# check to see if vms should be started after an unsuccessfull backup. if yes, continue. if no, continue. if input invalid, exit.
+# check to see if vms should be started after an unsuccessful backup. if yes, continue. if no, continue. if input invalid, exit.
 if [[ "$start_vm_after_failure" =~ ^(0|1)$ ]]; then
 
 	if [ "$start_vm_after_failure" -eq 0 ]; then
 
-		echo "$(date '+%Y-%m-%d %H:%M') information: start_vm_after_failure is $start_vm_after_failure. vms will not be started following an unsuccessfull backup." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
+		echo "$(date '+%Y-%m-%d %H:%M') information: start_vm_after_failure is $start_vm_after_failure. vms will not be started following an unsuccessful backup." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
 
 	elif [ "$start_vm_after_failure" -eq 1 ]; then
 
-		echo "$(date '+%Y-%m-%d %H:%M') information: start_vm_after_failure is $start_vm_after_failure. vms will be started following an unsuccessfull backup." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
+		echo "$(date '+%Y-%m-%d %H:%M') information: start_vm_after_failure is $start_vm_after_failure. vms will be started following an unsuccessful backup." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
 
 	fi
 
@@ -810,14 +843,14 @@ if [[ "$actually_copy_files" =~ ^(0|1)$ ]]; then
 
 	if [ "$actually_copy_files" -eq 0 ]; then
 
-		echo "$(date '+%Y-%m-%d %H:%M') warning: actually_copy_files flag is $actually_copy_files. no files will be coppied." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log" | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log" && errors="1"
+		echo "$(date '+%Y-%m-%d %H:%M') warning: actually_copy_files flag is $actually_copy_files. no files will be copied." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log" | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log" && errors="1"
 
 		# create a variable which tells rsync to do a dry-run.
 		rsync_dry_run_option="n"
 
 	elif [ "$actually_copy_files" -eq 1 ]; then
 
-		echo "$(date '+%Y-%m-%d %H:%M') information: actually_copy_files is $actually_copy_files. files will be coppied." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log" | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
+		echo "$(date '+%Y-%m-%d %H:%M') information: actually_copy_files is $actually_copy_files. files will be copied." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log" | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
 
 	fi
 
@@ -881,7 +914,7 @@ if [[ "$seconds_to_wait" =~ ^[0-9]+$ ]]; then
 
 	elif [ "$seconds_to_wait" -ge 30 ] && [ "$seconds_to_wait" -le 600 ]; then
 
-		echo "$(date '+%Y-%m-%d %H:%M') information: seconds_to_wait is $seconds_to_wait. this is probably a sufficent number of seconds to wait between shutdown checks." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
+		echo "$(date '+%Y-%m-%d %H:%M') information: seconds_to_wait is $seconds_to_wait. this is probably a sufficient number of seconds to wait between shutdown checks." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
 
 	fi
 
@@ -974,7 +1007,7 @@ echo "$(date '+%Y-%m-%d %H:%M') information: started attempt to backup $vms_to_b
 IFS=$'\n'
 
 
-# loop through the vms in the list and try and back up thier associated xml configurations and vdisk(s).
+# loop through the vms in the list and try and back up their associated xml configurations and vdisk(s).
 for vm in $vms_to_backup
 
 do
@@ -1042,7 +1075,7 @@ do
 	fi
 
 
-	# see if vdisks should be backed up, if the number of backukps is more than 1, and if disable delta sync is disabled.
+	# see if vdisks should be backed up, if the number of backups is more than 1, and if disable delta sync is disabled.
 	if [ "$backup_vdisks" -eq 1 ] && [ "$number_of_backups_to_keep" -ne 1 ] && [ "$disable_delta_sync" -ne 1 ]; then
 
 		# get the list of the vdisks associated with the vm and address them one by one.
@@ -1083,17 +1116,25 @@ do
 				new_disk=$(basename "$disk")
 
 				# check the extension of the disk to ensure only vdisks are copied.
-				# Do not use in conjunction with quemu-img conversion
+				# Do not use in conjunction with qemu-img conversion
 				if [ ! "${disk##*.}" == "img" ] && [ ! "${disk##*.}" == "qcow2" ]; then
 
-					echo "$(date '+%Y-%m-%d %H:%M') warning: $disk of $vm is not a vdisk. skipping." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log" && errors="1"
-					
-					if [ "$send_notifications" -eq 1 ]; then
+					if [ "$ignore_isos" -eq 1 ] && [ "${disk##*.}" == "iso" ]; then
 
-						/usr/local/emhttp/plugins/dynamix/scripts/notify -e "unraid-vmbackup_vm_backup" -s "unRAID VM Backup script" -d "no valid vdisk(s) for $vm" -i "warning" -m "$(date '+%Y-%m-%d %H:%M') warning: $disk of $vm is not a vdisk. skipping."
+						echo "$(date '+%Y-%m-%d %H:%M') information: $disk of $vm is an iso not a vdisk. skipping." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
+
+					else
+
+						echo "$(date '+%Y-%m-%d %H:%M') warning: $disk of $vm is not a vdisk. skipping." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log" && errors="1"
+
+						if [ "$send_notifications" -eq 1 ]; then
+
+							/usr/local/emhttp/plugins/dynamix/scripts/notify -e "unraid-vmbackup_vm_backup" -s "unRAID VM Backup script" -d "no valid vdisk(s) for $vm" -i "warning" -m "$(date '+%Y-%m-%d %H:%M') warning: $disk of $vm is not a vdisk. skipping."
+
+						fi
 
 					fi
-
+					
 					continue
 
 				fi
@@ -1220,7 +1261,7 @@ do
 
 		do
 
-			echo "$(date '+%Y-%m-%d %H:%M') information: clycle $i of $clean_shutdown_checks: waiting $seconds_to_wait seconds before checking if the vm has shutdown" | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
+			echo "$(date '+%Y-%m-%d %H:%M') information: cycle $i of $clean_shutdown_checks: waiting $seconds_to_wait seconds before checking if the vm has shutdown" | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
 
 			# wait x seconds based on how many seconds the user wants to wait between checks for a clean shutdown.
 			sleep $seconds_to_wait
@@ -1233,7 +1274,7 @@ do
 
 				echo "$(date '+%Y-%m-%d %H:%M') information: $vm is $vm_state" | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
 
-				# if we have already exhausted our wait time set by the script variables then its time to do soemthing else.
+				# if we have already exhausted our wait time set by the script variables then its time to do something else.
 				if [ $i = "$clean_shutdown_checks" ] ; then
 
 					# check if the user wants to kill the vm on failure of unclean shutdown.
@@ -1766,17 +1807,25 @@ do
 					new_disk=$(basename "$disk")
 
 					# check the extension of the disk to ensure only vdisks are copied.
-					# Do not use in conjunction with quemu-img conversion
+					# Do not use in conjunction with qemu-img conversion
 					if [ ! "${disk##*.}" == "img" ] && [ ! "${disk##*.}" == "qcow2" ]; then
 
-						echo "$(date '+%Y-%m-%d %H:%M') warning: $disk of $vm is not a vdisk. skipping." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log" && errors="1"
+						if [ "$ignore_isos" -eq 1 ] && [ "${disk##*.}" == "iso" ]; then
 
-						if [ "$send_notifications" -eq 1 ]; then
+							echo "$(date '+%Y-%m-%d %H:%M') information: $disk of $vm is an iso not a vdisk. skipping." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
 
-							/usr/local/emhttp/plugins/dynamix/scripts/notify -e "unraid-vmbackup_vm_backup" -s "unRAID VM Backup script" -d "no valid vdisk(s) for $vm" -i "warning" -m "$(date '+%Y-%m-%d %H:%M') warning: $disk of $vm is not a vdisk. skipping."
+						else
+
+							echo "$(date '+%Y-%m-%d %H:%M') warning: $disk of $vm is not a vdisk. skipping." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log" && errors="1"
+
+							if [ "$send_notifications" -eq 1 ]; then
+
+								/usr/local/emhttp/plugins/dynamix/scripts/notify -e "unraid-vmbackup_vm_backup" -s "unRAID VM Backup script" -d "no valid vdisk(s) for $vm" -i "warning" -m "$(date '+%Y-%m-%d %H:%M') warning: $disk of $vm is not a vdisk. skipping."
+
+							fi
 
 						fi
-
+						
 						continue
 
 					fi
@@ -2033,7 +2082,7 @@ do
 		fi
 
 
-		# if start_vm_after_backup is set to 1 then start the vm but dont check that it has been successfull.
+		# if start_vm_after_backup is set to 1 then start the vm but dont check that it has been successful.
 		if [ "$start_vm_after_backup" -eq 1 ]; then
 
 			echo "$(date '+%Y-%m-%d %H:%M') action: start_vm_after_backup is $start_vm_after_backup. starting $vm." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
@@ -2156,7 +2205,7 @@ do
 		fi
 
 
-		# if start_vm_after_failure is set to 1 then start the vm but dont check that it has been successfull.
+		# if start_vm_after_failure is set to 1 then start the vm but dont check that it has been successful.
 		if [ "$start_vm_after_failure" -eq 1 ]; then
 
 			echo "$(date '+%Y-%m-%d %H:%M') action: start_vm_after_failure is $start_vm_after_failure starting $vm." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
@@ -2194,7 +2243,7 @@ do
 	# check to see how many days backups should be kept.
 	if [ "$number_of_days_to_keep_backups" -eq 0 ]; then
 	
-		echo "$(date '+%Y-%m-%d %H:%M') information: nubmer of days to keep backups set to indefinitely." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
+		echo "$(date '+%Y-%m-%d %H:%M') information: number of days to keep backups set to indefinitely." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
 
 	else
 
