fixed vdisk copying with delta sync and new vdisk skip error

diff --git a/script b/script
--- a/script
+++ b/script
@@ -1093,7 +1093,6 @@ do
 
 		fi
 
-
 		# get vdisk names to check on current backups
 		for disk in $vdisks
 
@@ -1103,6 +1102,7 @@ do
 
 				# check to see if disk should be skipped.
 				skip_disk="0"
+				
 				for skipvdisk_name in $vdisks_to_skip
 
 				do
@@ -1119,6 +1119,17 @@ do
 
 				# get the filename of the disk without the path.
 				new_disk=$(basename "$disk")
+
+				# get the disk number and extension
+				unset -v disk_number
+
+				vdisknameregex="[0-9]+\.(img|qcow2)"
+
+				if [[ $disk =~ $vdisknameregex ]]; then
+
+					disk_number=${BASH_REMATCH[0]}
+
+				fi
 
 				# check the extension of the disk to ensure only vdisks are copied.
 				# Do not use in conjunction with qemu-img conversion
@@ -1144,18 +1155,33 @@ do
 
 				fi
 				
+				# skip the vdisk if skip_disk is set to 1
 				if [ "$skip_disk" -ne 1 ]; then
 
-					# get the most recent vdisk file.
+					# unset variable for the most recent vdisk file.
 					unset -v newest_vdisk_file
 
-					for diskimage in "$backup_location/$vm/"*.{img,qcow2}
+					# see if disk_number is empty. if not, set to wildcard.
+					if [ -z "$disk_number" ]; then
+					
+						disk_number='.@(img|qcow2)'
+
+					fi
+
+					# enable extended globbing
+					shopt -s extglob
+
+					# get the most recent vdisk file.
+					for diskimage in "$backup_location/$vm/"*$disk_number
 
 					do
 
 						[[ $diskimage -nt $newest_vdisk_file ]] && newest_vdisk_file=$diskimage
 
 					done
+
+					# disable extended globbing
+					shopt -u extglob
 
 					# check to see if a backup already exists for this vdisk and make a copy of it before shutting down the guest.
 					if [ -f "$newest_vdisk_file" ]; then
@@ -1229,7 +1255,7 @@ do
 						fi
 
 					fi
-
+					
 				fi
 
 			fi
@@ -1811,6 +1837,22 @@ do
 
 				if [ ! "$disk" == "Source" ]; then
 
+					# check to see if disk should be skipped.
+					skip_disk="0"
+					
+					for skipvdisk_name in $vdisks_to_skip
+
+					do
+
+						if [ "$skipvdisk_name" == "$disk" ]; then
+
+							skip_disk="1"
+
+							echo "$(date '+%Y-%m-%d %H:%M') information: $disk for $vm was found in vdisks_to_skip. skipping disk." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
+
+						fi
+
+					done
 
 					# get the filename of the disk without the path.
 					new_disk=$(basename "$disk")
@@ -1839,46 +1881,14 @@ do
 
 					fi
 
-					# copy or pretend to copy the vdisk to the backup location specified by the user.
-					# check if only one non-timestamped backup is being kept. if so, perform cp -f without a timestamp. if not, continue as normal.
-					if [ "$timestamp_files" -eq 0 ]  && [ "$number_of_backups_to_keep" -eq 1 ]; then
+					# skip the vdisk if skip_disk is set to 1
+					if [ "$skip_disk" -ne 1 ]; then
 
-						if [ "$rsync_only" -eq 1 ]; then
+						# copy or pretend to copy the vdisk to the backup location specified by the user.
+						# check if only one non-timestamped backup is being kept. if so, perform cp -f without a timestamp. if not, continue as normal.
+						if [ "$timestamp_files" -eq 0 ]  && [ "$number_of_backups_to_keep" -eq 1 ]; then
 
-							rsync -av$rsync_dry_run_option --sparse "$disk" "$backup_location/$vm/$new_disk"
-
-							# get rsync result and send notification
-							if [[ $? -eq 1 ]]; then
-
-								if [ "$send_notifications" -eq 1 ]; then
-
-									/usr/local/emhttp/plugins/dynamix/scripts/notify -e "unraid-vmbackup_vm_backup" -s "unRAID VM Backup script" -d "$vm vdisk backup failed" -i "alert" -m "$(date '+%Y-%m-%d %H:%M') failure: copy of backup of $disk to $backup_location/$vm/$new_disk failed."
-
-								fi
-
-							fi
-
-						else
-
-							cp -afv --sparse=always "$disk" "$backup_location/$vm/$new_disk"
-
-						fi
-
-						# make sure copy has current date/time for modified attribute so that removing old disks by date will work.
-						touch -d "now" "$backup_location/$vm/$new_disk"
-
-						# check to see if compare_files is enabled. if yes, check for vdisk differences.
-						if [ "$compare_files" -eq 1 ]; then
-
-							if ! cmp -s "$disk" "$backup_location/$vm/$new_disk"; then
-
-								echo "$(date '+%Y-%m-%d %H:%M') warning: $vm vdisk backup file is different than source file. attempting slower rsync backup." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log" && errors="1"
-
-								if [ "$send_notifications" -eq 1 ]; then
-
-									/usr/local/emhttp/plugins/dynamix/scripts/notify -e "unraid-vmbackup_vm_backup" -s "unRAID VM Backup script" -d "$vm vdisk compare failed" -i "warning" -m "$(date '+%Y-%m-%d %H:%M') warning: vdisk backup file is different than source file. attempting slower rsync backup."
-
-								fi
+							if [ "$rsync_only" -eq 1 ]; then
 
 								rsync -av$rsync_dry_run_option --sparse "$disk" "$backup_location/$vm/$new_disk"
 
@@ -1893,108 +1903,113 @@ do
 
 								fi
 
-								# make sure copy has current date/time for modified attribute so that removing old disks by date will work.
-								touch -d "now" "$backup_location/$vm/$new_disk"
+							else
+
+								cp -afv --sparse=always "$disk" "$backup_location/$vm/$new_disk"
+
+							fi
+
+							# make sure copy has current date/time for modified attribute so that removing old disks by date will work.
+							touch -d "now" "$backup_location/$vm/$new_disk"
+
+							# check to see if compare_files is enabled. if yes, check for vdisk differences.
+							if [ "$compare_files" -eq 1 ]; then
 
 								if ! cmp -s "$disk" "$backup_location/$vm/$new_disk"; then
 
-									echo "$(date '+%Y-%m-%d %H:%M') failure: $vm vdisk backup file failed second comparison." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log" && errors="1"
+									echo "$(date '+%Y-%m-%d %H:%M') warning: $vm vdisk backup file is different than source file. attempting slower rsync backup." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log" && errors="1"
 
 									if [ "$send_notifications" -eq 1 ]; then
 
-										/usr/local/emhttp/plugins/dynamix/scripts/notify -e "unraid-vmbackup_vm_backup" -s "unRAID VM Backup script" -d "$vm vdisk second compare failed" -i "alert" -m "$(date '+%Y-%m-%d %H:%M') failure: vdisk backup file failed second comparison."
+										/usr/local/emhttp/plugins/dynamix/scripts/notify -e "unraid-vmbackup_vm_backup" -s "unRAID VM Backup script" -d "$vm vdisk compare failed" -i "warning" -m "$(date '+%Y-%m-%d %H:%M') warning: vdisk backup file is different than source file. attempting slower rsync backup."
+
+									fi
+
+									rsync -av$rsync_dry_run_option --sparse "$disk" "$backup_location/$vm/$new_disk"
+
+									# get rsync result and send notification
+									if [[ $? -eq 1 ]]; then
+
+										if [ "$send_notifications" -eq 1 ]; then
+
+											/usr/local/emhttp/plugins/dynamix/scripts/notify -e "unraid-vmbackup_vm_backup" -s "unRAID VM Backup script" -d "$vm vdisk backup failed" -i "alert" -m "$(date '+%Y-%m-%d %H:%M') failure: copy of backup of $disk to $backup_location/$vm/$new_disk failed."
+
+										fi
+
+									fi
+
+									# make sure copy has current date/time for modified attribute so that removing old disks by date will work.
+									touch -d "now" "$backup_location/$vm/$new_disk"
+
+									if ! cmp -s "$disk" "$backup_location/$vm/$new_disk"; then
+
+										echo "$(date '+%Y-%m-%d %H:%M') failure: $vm vdisk backup file failed second comparison." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log" && errors="1"
+
+										if [ "$send_notifications" -eq 1 ]; then
+
+											/usr/local/emhttp/plugins/dynamix/scripts/notify -e "unraid-vmbackup_vm_backup" -s "unRAID VM Backup script" -d "$vm vdisk second compare failed" -i "alert" -m "$(date '+%Y-%m-%d %H:%M') failure: vdisk backup file failed second comparison."
+
+										fi
+
+									else
+
+										echo "$(date '+%Y-%m-%d %H:%M') information: $vm vdisk backup file passed second comparison. moving on." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
 
 									fi
 
 								else
 
-									echo "$(date '+%Y-%m-%d %H:%M') information: $vm vdisk backup file passed second comparison. moving on." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
-
-								fi
-
-							else
-
-								echo "$(date '+%Y-%m-%d %H:%M') information: $vm vdisk backup file matches source file. moving on." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
-
-							fi
-
-						fi
-
-					else
-
-						# check to see if an existing backup was already copied. if so, use rsync. if not, use cp.
-						if [ ! -f "$backup_location/$vm/$timestamp$new_disk" ]; then
-
-							if [ "$rsync_only" -eq 1 ]; then
-
-								rsync -av$rsync_dry_run_option --sparse "$disk" "$backup_location/$vm/$timestamp$new_disk"
-
-								# get rsync result and send notification
-								if [[ $? -eq 1 ]]; then
-
-									if [ "$send_notifications" -eq 1 ]; then
-
-										/usr/local/emhttp/plugins/dynamix/scripts/notify -e "unraid-vmbackup_vm_backup" -s "unRAID VM Backup script" -d "$vm vdisk backup failed" -i "alert" -m "$(date '+%Y-%m-%d %H:%M') failure: copy of backup of $disk to $backup_location/$vm/$timestamp$new_disk failed."
-
-									fi
-
-								fi
-
-							else
-
-								cp -av --sparse=always "$disk" "$backup_location/$vm/$timestamp$new_disk"
-
-								# get cp result and send notification
-								if [[ $? -eq 1 ]]; then
-
-									if [ "$send_notifications" -eq 1 ]; then
-									
-										/usr/local/emhttp/plugins/dynamix/scripts/notify -e "unraid-vmbackup_vm_backup" -s "unRAID VM Backup script" -d "copy $vm backup failed" -i "alert" -m "$(date '+%Y-%m-%d %H:%M') failure: copy of backup of $disk vdisk to $backup_location/$vm/$timestamp$new_disk failed."
-
-									fi
+									echo "$(date '+%Y-%m-%d %H:%M') information: $vm vdisk backup file matches source file. moving on." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
 
 								fi
 
 							fi
-
-							# make sure copy has current date/time for modified attribute so that removing old disks by date will work.
-							touch -d "now" "$backup_location/$vm/$timestamp$new_disk"
 
 						else
 
-							# check to see if delta sync is disabled. if so, run cp. if not, continue to rsync delta sync.
-							rsync -av$rsync_dry_run_option --inplace --no-whole-file "$disk" "$backup_location/$vm/$timestamp$new_disk"
+							# check to see if an existing backup was already copied. if so, use rsync. if not, use cp.
+							if [ ! -f "$backup_location/$vm/$timestamp$new_disk" ]; then
 
-							# get rsync result and send notification
-							if [[ $? -eq 1 ]]; then
+								# check to see if rsync_only.
+								if [ "$rsync_only" -eq 1 ]; then
 
-								if [ "$send_notifications" -eq 1 ]; then
+									rsync -av$rsync_dry_run_option --sparse "$disk" "$backup_location/$vm/$timestamp$new_disk"
 
-									/usr/local/emhttp/plugins/dynamix/scripts/notify -e "unraid-vmbackup_vm_backup" -s "unRAID VM Backup script" -d "$vm vdisk backup failed" -i "alert" -m "$(date '+%Y-%m-%d %H:%M') failure: copy of backup of $disk to $backup_location/$vm/$timestamp$new_disk failed."
+									# get rsync result and send notification
+									if [[ $? -eq 1 ]]; then
+
+										if [ "$send_notifications" -eq 1 ]; then
+
+											/usr/local/emhttp/plugins/dynamix/scripts/notify -e "unraid-vmbackup_vm_backup" -s "unRAID VM Backup script" -d "$vm vdisk backup failed" -i "alert" -m "$(date '+%Y-%m-%d %H:%M') failure: copy of backup of $disk to $backup_location/$vm/$timestamp$new_disk failed."
+
+										fi
+
+									fi
+
+								else
+
+									cp -av --sparse=always "$disk" "$backup_location/$vm/$timestamp$new_disk"
+
+									# get cp result and send notification
+									if [[ $? -eq 1 ]]; then
+
+										if [ "$send_notifications" -eq 1 ]; then
+										
+											/usr/local/emhttp/plugins/dynamix/scripts/notify -e "unraid-vmbackup_vm_backup" -s "unRAID VM Backup script" -d "copy $vm backup failed" -i "alert" -m "$(date '+%Y-%m-%d %H:%M') failure: copy of backup of $disk vdisk to $backup_location/$vm/$timestamp$new_disk failed."
+
+										fi
+
+									fi
 
 								fi
 
-							fi
+								# make sure copy has current date/time for modified attribute so that removing old disks by date will work.
+								touch -d "now" "$backup_location/$vm/$timestamp$new_disk"
 
-							# make sure copy has current date/time for modified attribute so that removing old disks by date will work.
-							touch -d "now" "$backup_location/$vm/$timestamp$new_disk"
+							else
 
-						fi
-
-						# check to see if compare_files is enabled. if yes, check for vdisk differences.
-						if [ "$compare_files" -eq 1 ]; then
-
-							if ! cmp -s "$disk" "$backup_location/$vm/$timestamp$new_disk"; then
-
-								echo "$(date '+%Y-%m-%d %H:%M') warning: $vm vdisk backup file is different than source file. attempting slower rsync backup." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log" && errors="1"
-
-								if [ "$send_notifications" -eq 1 ]; then
-
-									/usr/local/emhttp/plugins/dynamix/scripts/notify -e "unraid-vmbackup_vm_backup" -s "unRAID VM Backup script" -d "$vm vdisk compare failed" -i "warning" -m "$(date '+%Y-%m-%d %H:%M') warning: vdisk backup file is different than source file. attempting slower rsync backup."
-
-								fi
-
-								rsync -av$rsync_dry_run_option --sparse "$disk" "$backup_location/$vm/$timestamp$new_disk"
+								# use rsync because delta_sync was enabled.
+								rsync -av$rsync_dry_run_option --inplace --no-whole-file "$disk" "$backup_location/$vm/$timestamp$new_disk"
 
 								# get rsync result and send notification
 								if [[ $? -eq 1 ]]; then
@@ -2010,40 +2025,73 @@ do
 								# make sure copy has current date/time for modified attribute so that removing old disks by date will work.
 								touch -d "now" "$backup_location/$vm/$timestamp$new_disk"
 
+							fi
+
+							# check to see if compare_files is enabled. if yes, check for vdisk differences.
+							if [ "$compare_files" -eq 1 ]; then
+
 								if ! cmp -s "$disk" "$backup_location/$vm/$timestamp$new_disk"; then
 
-									echo "$(date '+%Y-%m-%d %H:%M') failure: $vm vdisk backup file failed second comparison." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log" && errors="1"
+									echo "$(date '+%Y-%m-%d %H:%M') warning: $vm vdisk backup file is different than source file. attempting slower rsync backup." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log" && errors="1"
 
 									if [ "$send_notifications" -eq 1 ]; then
 
-										/usr/local/emhttp/plugins/dynamix/scripts/notify -e "unraid-vmbackup_vm_backup" -s "unRAID VM Backup script" -d "$vm vdisk second compare failed" -i "alert" -m "$(date '+%Y-%m-%d %H:%M') failure: vdisk backup file failed second comparison."
+										/usr/local/emhttp/plugins/dynamix/scripts/notify -e "unraid-vmbackup_vm_backup" -s "unRAID VM Backup script" -d "$vm vdisk compare failed" -i "warning" -m "$(date '+%Y-%m-%d %H:%M') warning: vdisk backup file is different than source file. attempting slower rsync backup."
+
+									fi
+
+									rsync -av$rsync_dry_run_option --sparse "$disk" "$backup_location/$vm/$timestamp$new_disk"
+
+									# get rsync result and send notification
+									if [[ $? -eq 1 ]]; then
+
+										if [ "$send_notifications" -eq 1 ]; then
+
+											/usr/local/emhttp/plugins/dynamix/scripts/notify -e "unraid-vmbackup_vm_backup" -s "unRAID VM Backup script" -d "$vm vdisk backup failed" -i "alert" -m "$(date '+%Y-%m-%d %H:%M') failure: copy of backup of $disk to $backup_location/$vm/$timestamp$new_disk failed."
+
+										fi
+
+									fi
+
+									# make sure copy has current date/time for modified attribute so that removing old disks by date will work.
+									touch -d "now" "$backup_location/$vm/$timestamp$new_disk"
+
+									if ! cmp -s "$disk" "$backup_location/$vm/$timestamp$new_disk"; then
+
+										echo "$(date '+%Y-%m-%d %H:%M') failure: $vm vdisk backup file failed second comparison." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log" && errors="1"
+
+										if [ "$send_notifications" -eq 1 ]; then
+
+											/usr/local/emhttp/plugins/dynamix/scripts/notify -e "unraid-vmbackup_vm_backup" -s "unRAID VM Backup script" -d "$vm vdisk second compare failed" -i "alert" -m "$(date '+%Y-%m-%d %H:%M') failure: vdisk backup file failed second comparison."
+
+										fi
+
+									else
+
+										echo "$(date '+%Y-%m-%d %H:%M') information: $vm vdisk backup file passed second comparison. moving on." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
 
 									fi
 
 								else
 
-									echo "$(date '+%Y-%m-%d %H:%M') information: $vm vdisk backup file passed second comparison. moving on." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
+									echo "$(date '+%Y-%m-%d %H:%M') information: $vm vdisk backup file matches source file. moving on." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
 
 								fi
-
-							else
-
-								echo "$(date '+%Y-%m-%d %H:%M') information: $vm vdisk backup file matches source file. moving on." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
 
 							fi
 
 						fi
 
-					fi
+						# send a message to the user based on whether there was an actual copy or a dry-run.
+						if [ "$actually_copy_files" -eq 0 ]; then
 
-					# send a message to the user based on whether there was an actual copy or a dry-run.
-					if [ "$actually_copy_files" -eq 0 ]; then
+							echo "$(date '+%Y-%m-%d %H:%M') information: dry-run backup of $new_disk vdisk to $backup_location/$vm/$timestamp$new_disk complete." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
 
-						echo "$(date '+%Y-%m-%d %H:%M') information: dry-run backup of $new_disk vdisk to $backup_location/$vm/$timestamp$new_disk complete." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
+						else
 
-					else
+							echo "$(date '+%Y-%m-%d %H:%M') information: backup of $new_disk vdisk to $backup_location/$vm/$timestamp$new_disk complete." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
 
-						echo "$(date '+%Y-%m-%d %H:%M') information: backup of $new_disk vdisk to $backup_location/$vm/$timestamp$new_disk complete." | tee -a "$backup_location/$log_file_subfolder$timestamp""unraid-vmbackup.log"
+						fi
 
 					fi
 
